volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${LOGIN}/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${LOGIN}/data/wordpress
      o: bind
      type: none

  # BONUS
  netdata:
    name: netdata
    driver: local
    driver_opts:
      device: /home/${LOGIN}/data/netdata
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure

  # BONUS
  redis:
    container_name: redis
    build: requirements/bonus/redis
    image: redis:42
    networks:
      - inception
    restart: on-failure

  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    image: ftp:42
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:42
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure

  netdata:
    container_name: netdata
    build: ./requirements/bonus/netdata
    image: netdata:42
    pid: host
    networks:
      - inception
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - "19999:19999"
    volumes:
      - netdata:/var/lib/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge