volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/lguerbig/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/lguerbig/data/wordpress
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:custom
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:custom
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:custom
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge